baseURL = "https://feily.tech/"
languageCode = "en-us"
title = "Feily Zhang"
theme = "ezhil"
paginate = 5

copyright = "© Copyright feily.tech"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#googleAnalytics = "UA-123-45"
#disqusShortname = "ezhil-demo"

summaryLength = 0

[params]
	subtitle = "Software Developer, Machine Learning, Astronomy Enthusiast."
	disableDisqusTypes = ["page"]
	featherIconsCDN = true
	mode = "auto" # "dark", "auto", "light"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/FeilyZhang"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/FeilyZhang"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
